### PR TITLE
Feature/mvp map

### PR DESCRIPTION
**Pull request by nmuldavin**
Put in a very basic map to start facilitating discussions about presentation / UX, etc. There are many open questions!

Some that come to mind for me:

- How do we visually represent affordability for you vs affordability for others? In this version, dark blue means affordable for you, outlined in black means affordable for others. We are somewhat limited by the available styling options here. Crosshatching might be possible with a leaflet extension but we shouldn't count on it.

 - What kind of busy / waiting thing do we need while calls are being made? 

 - What kind of auxiliary info do we want to show about the map? 

I'm sure there are more. I think this will make it much more tangible so that such discussions are productive.

Todo, programming wise: 

 - Tests for new components
 - Potentially debounce income-slider's updating of the map so it doesn't fire off updates all the time. I think it's a little laggy, although not as bad as I thought it would be.
- Lots of styling

screen shot 2017-04-26 at 3 24 58 pm

### CODE REVIEW

**Comment by DingoEatingFuzz** [comment]
An immediate observation is that this is using React Leaflet directly rather than the map in the component library.

I'm sure there's a reason for that, can you explain the decision?

**Comment by nmuldavin** [comment]
Yes, the leaflet map in the component library now takes URL and attribution for the tile layer as props. To use the cartodb tile layer I though most closely matched the wireframe, I also needed to pass subdomain and max zoom to the tile lsyer component. I think that in cleanup phase after demo day we should compare our map to everyone else's and try to consolidate but in the interest of getting it done I figured a pr here was better that a pr there that other teams might not need, and waiting for npm deploy

**Comment by JohnTasto** [comment]
I haven't used React Leaflet or geojson before - will it work to add an onClick handler to Neighborhood to select neighborhoods for the detail view?

**Review by DingoEatingFuzz — APPROVED** [review]
I think we'll want to reconsider how we are organizing components at some point (right now it's a mix of pages and presentational pieces), but I'm cool with merging this.

**Comment by DingoEatingFuzz** [comment]
> will it work to add an onClick handler to Neighborhood to select neighborhoods for the detail view?

Yes! I just tested it out:

image

image

**Comment by JohnTasto** [comment]
Nice. Thanks!

**Pull request merged**
