### PR TITLE
#32 Pull in Voter Registration Gifs and copy

### PR DESCRIPTION
**Pull request by JohnTasto**
A couple long lines, but the linter doesn't seem to care.

### CODE REVIEW

**Comment by nmuldavin** [comment]
Nice work! Some of the images seem skewed a little, post demo day maybe we can work on getting different versions in, or better yet including live charts rather than gifs

**Comment by JohnTasto** [comment]
Thanks.

Skewed? I didn't notice that - what are you referring to? Is it fixable with styling?

I don't like how some of them have grey backgrounds and some have white, plus they add like 6mb to our page load, so yeah, it would be much better to have live charts!

**Comment by nmuldavin** [comment]
Just this one mainly: https://s3-us-west-2.amazonaws.com/hacko-housing-staging/TravelingYouthStats.png. I think it's the pies themselves so we can't fix it with style. It's not a super big deal for now

**Comment by JohnTasto** [comment]
Oh yeah, you're right. Well we could squash it a bit with CSS, but I'm not sure how to do that responsively.

**Pull request merged**
