### PR TITLE
Update component library

### PR DESCRIPTION
**Pull request by DingoEatingFuzz**
Also updated the page to use a StoryCard.

image

### CODE REVIEW

**Comment by JohnTasto** [comment]
From Travis CI:

```
/home/travis/build/hackoregon/housing-frontend/src/client.js (2/0)
  ✖  2:1  Unexpected '!' in '!style-loader!css-loader!@hackoregon/component-library/assets/leaflet.css'. Do not use import syntax to configure webpack loaders  import/no-webpack-loader-syntax
  ✖  2:8  Unable to resolve path to module '!style-loader!css-loader!@hackoregon/component-library/assets/leaflet.css'                                          import/no-unresolved
/home/travis/build/hackoregon/housing-frontend/src/components/App/index.js (1/0)
  ✖  79:1  Line 79 exceeds the maximum line length of 100  max-len
✖ 3 errors (4:36:38 AM)
```

**Comment by DingoEatingFuzz** [comment]
Yeeeeah. Those first two lines are correct and the linter doesn't know what's up. I'll add an ignore annotation.

The second one is too strict for templates, imo, but I'll reformat it and push again.

**Comment by meganmckissack** [comment]
css loader strikes again!

**Comment by DingoEatingFuzz** [comment]
Merging this 🎉 💃

**Pull request merged**
