### PR TITLE
Match jsx files with the webpack dev babel loader

### PR DESCRIPTION
**Pull request by DingoEatingFuzz**

### CODE REVIEW

**Comment by DavideDaniel** [comment]
I would recommend not using the Jsx extension. It's a holdover from a time when react would only compile from jsx files. Now that it works with js, it's a performance hit to use the jsx extension.

**Comment by DavideDaniel** [comment]
I'm gonna leave this open because I realized it maybe due to some dependency. Feel free to air the motivations for the change.

**Comment by DingoEatingFuzz** [comment]
The immediate motivation is webpack wasn't happy until I did it 😄. But it was complaining about [the jsx file in our own component library](https://github.com/hackoregon/component-library/blob/master/src/Navigation/NavRouterLink.jsx), so we could also just change that extension.

If we do that, I think we should update the prod webpack config to also only match js files.

**Comment by DavideDaniel** [comment]
I like that solution a lot more. If a pr isn't in when I get in later, I'll check it in.

**Comment by DavideDaniel** [comment]
https://github.com/hackoregon/component-library/commit/43aa395964bc43e2855d15cc92cd70c6d03d06a1 was merged in earlier.. good call out..

**Pull request closed without merging**
